package com.example.astro

import com.example.data.model.RashifalData

object RashifalProvider {

    fun getDailyHoroscope(): List<RashifalData> {
        return listOf(
            RashifalData(
                rashiId = 1, rashiNameEn = "Aries", rashiNameHi = "मेष (Aries)", symbol = "♈",
                elementHi = "अग्नि (Fire)", rulerHi = "मंगल (Mars)", ratingStars = 5,
                luckyNumber = 9, luckyColorEn = "Red", luckyColorHi = "लाल एवं नारंगी", luckyStoneHi = "मूंगा (Red Coral)",
                generalReadingHi = "आज का दिन आपके लिए ऊर्जा एवं नव उत्साह लेकर आया है। साहसिक निर्णयों में सफलता मिलेगी। कार्यक्षेत्र में सहकर्मियों का पूर्ण सहयोग प्राप्त होगा।",
                generalReadingEn = "Today brings high energy and renewed enthusiasm. Courageous decisions will yield success.",
                careerReadingHi = "करियर में पदोन्नति अथवा नए प्रोजेक्ट की जिम्मेदारी मिल सकती है। अधिकारियों से प्रशंसा प्राप्त होगी।",
                careerReadingEn = "Promotions or new responsibilities at work are likely. High appreciation from seniors.",
                healthReadingHi = "स्वास्थ्य उत्तम रहेगा। प्राणायाम व योग से मानसिक ताजगी बनी रहेगी।",
                healthReadingEn = "Health remains excellent. Stay hydrated and practice yoga.",
                loveReadingHi = "दांपत्य जीवन में मधुरता रहेगी। जीवनसाथी के साथ शाम बिताने का अवसर मिलेगा।",
                loveReadingEn = "Harmonious marital relationship. Enjoy a romantic evening with spouse.",
                financeReadingHi = "आर्थिक पक्ष मजबूत रहेगा। अटका हुआ धन वापस मिल सकता है।",
                financeReadingEn = "Financial position is strong. Pending dues are likely to be recovered."
            ),
            RashifalData(
                rashiId = 2, rashiNameEn = "Taurus", rashiNameHi = "वृषभ (Taurus)", symbol = "♉",
                elementHi = "पृथ्वी (Earth)", rulerHi = "शुक्र (Venus)", ratingStars = 4,
                luckyNumber = 6, luckyColorEn = "White", luckyColorHi = "सफेद एवं हल्का गुलाबी", luckyStoneHi = "हीरा / ओपल",
                generalReadingHi = "धैर्य एवं संयम से काम लें। पारिवारिक वातावरण सुखद रहेगा। नए निवेश के लिए दिन अनुकूल है।",
                generalReadingEn = "Act with patience and composure. Family environment will remain joyful and supportive.",
                careerReadingHi = "व्यापार में नए साझेदार जुड़ सकते हैं। कार्यस्थल पर वाणी की मधुरता बनाए रखें।",
                careerReadingEn = "Business expansion opportunities through new partners. Keep polite workplace communication.",
                healthReadingHi = "खानपान पर ध्यान दें। गले में हल्की खराश की संभावना है।",
                healthReadingEn = "Pay attention to your diet and avoid cold beverages.",
                loveReadingHi = "प्रेम संबंधों में प्रगाढ़ता आएगी। परस्पर विश्वास बढ़ेगा।",
                loveReadingEn = "Deeper bonding in romantic relationships with mutual trust.",
                financeReadingHi = "भौतिक सुख-सुविधाओं पर व्यय संभव है। बजट बनाकर चलें।",
                financeReadingEn = "Spending on luxury comforts. Keep a balanced household budget."
            ),
            RashifalData(
                rashiId = 3, rashiNameEn = "Gemini", rashiNameHi = "मिथुन (Gemini)", symbol = "♊",
                elementHi = "वायु (Air)", rulerHi = "बुध (Mercury)", ratingStars = 4,
                luckyNumber = 5, luckyColorEn = "Green", luckyColorHi = "हरा एवं तोतिया", luckyStoneHi = "पन्ना (Emerald)",
                generalReadingHi = "बौद्धिक कार्यों एवं पठन-पाठन में रुचि बढ़ेगी। मित्रों से शुभ समाचार प्राप्त होगा।",
                generalReadingEn = "High intellect and curiosity today. Good news expected from close friends.",
                careerReadingHi = "आईटी, मीडिया व लेखन क्षेत्र के लोगों को विशेष सफलता। आईटी डील्स फाइनल होंगी।",
                careerReadingEn = "Great success for IT, media, and creative writing professionals.",
                healthReadingHi = "मानसिक तनाव से बचें। पर्याप्त नींद लेना आवश्यक है।",
                healthReadingEn = "Avoid overthinking and ensure 7-8 hours of sound sleep.",
                loveReadingHi = "जीवनसाथी से वैचारिक मतभेद दूर होंगे। साथ घूमने का प्लान बनेगा।",
                loveReadingEn = "Resolving differences with partner; plan a weekend outing.",
                financeReadingHi = "शेयर बाज़ार या म्यूचुअल फंड से लाभ के योग हैं।",
                financeReadingEn = "Profits indicated from long-term stock market or mutual fund investments."
            ),
            RashifalData(
                rashiId = 4, rashiNameEn = "Cancer", rashiNameHi = "कर्क (Cancer)", symbol = "♋",
                elementHi = "जल (Water)", rulerHi = "चन्द्र (Moon)", ratingStars = 5,
                luckyNumber = 2, luckyColorEn = "Silver", luckyColorHi = "चांदी एवं क्रीम", luckyStoneHi = "मोती (Pearl)",
                generalReadingHi = "भावनाओं में बहने से बचें। माताजी का आशीर्वाद प्राप्त होगा। गृह सौन्दर्यीकरण पर ध्यान देंगे।",
                generalReadingEn = "Stay grounded emotionally. Blessings from mother bring peace and joy.",
                careerReadingHi = "सरकारी कार्य समय पर पूर्ण होंगे। नए प्रोजेक्ट्स शुरू करने के लिए दिन उत्तम है।",
                careerReadingEn = "Government work clears smoothly. Excellent time to launch fresh initiatives.",
                healthReadingHi = "स्वास्थ्य में सुधार होगा। योग व मेडिटेशन से लाभ मिलेगा।",
                healthReadingEn = "Health improves significantly with morning meditation.",
                loveReadingHi = "पारिवारिक रिश्तों में घनिष्ठता बढ़ेगी। जीवनसाथी का पूर्ण सहयोग मिलेगा।",
                loveReadingEn = "Family bonds strengthen. Spouse offers complete emotional backing.",
                financeReadingHi = "अचल संपत्ति या भूमि-भवन क्रय के योग बन रहे हैं।",
                financeReadingEn = "Favorable planetary alignment for property or vehicle purchases."
            ),
            RashifalData(
                rashiId = 5, rashiNameEn = "Leo", rashiNameHi = "सिंह (Leo)", symbol = "♌",
                elementHi = "अग्नि (Fire)", rulerHi = "सूर्य (Sun)", ratingStars = 5,
                luckyNumber = 1, luckyColorEn = "Gold", luckyColorHi = "सुनहरा व केसरिया", luckyStoneHi = "माणिक्य (Ruby)",
                generalReadingHi = "आपका प्रभाव एवं मान-सम्मान बढ़ेगा। सामाजिक क्षेत्र में नेतृत्व का अवसर मिलेगा।",
                generalReadingEn = "Your charisma and respect shine brightly. Leadership roles naturally come to you.",
                careerReadingHi = "उच्च अधिकारियों से सहयोग मिलेगा। व्यापार में बड़ा लाभ संभव है।",
                careerReadingEn = "Strong support from superiors. Major commercial gain in business.",
                healthReadingHi = "आत्मविश्वास से परिपूर्ण रहेंगे। दिनभर ऊर्जा बनी रहेगी।",
                healthReadingEn = "Full of vitality and positive aura throughout the day.",
                loveReadingHi = "प्रेम जीवन में नया मोड़ आएगा। साथी की ओर से सरप्राइज मिल सकता है।",
                loveReadingEn = "Exciting turn in love life; sweet surprise expected from partner.",
                financeReadingHi = "आय के नए स्रोत बनेंगे। पुराना कर्ज चुकाने में सफलता।",
                financeReadingEn = "New income streams open up. Successful repayment of old loans."
            ),
            RashifalData(
                rashiId = 6, rashiNameEn = "Virgo", rashiNameHi = "कन्या (Virgo)", symbol = "♍",
                elementHi = "पृथ्वी (Earth)", rulerHi = "बुध (Mercury)", ratingStars = 4,
                luckyNumber = 5, luckyColorEn = "Yellow", luckyColorHi = "हल्का पीला", luckyStoneHi = "पन्ना (Emerald)",
                generalReadingHi = "बारीकी एवं योजनाबद्ध तरीके से काम करें। संतान पक्ष से खुशी का समाचार मिलेगा।",
                generalReadingEn = "Attention to detail brings perfection. Good news regarding children.",
                careerReadingHi = "बैंकिंग, एकाउंट्स एवं शिक्षा क्षेत्र में विशेष सफलता।",
                careerReadingEn = "High performance in banking, accounting, and educational domains.",
                healthReadingHi = "पाचन तंत्र का ध्यान रखें। सात्विक आहार लें।",
                healthReadingEn = "Eat fresh home-cooked light meals to maintain healthy digestion.",
                loveReadingHi = "दाम्पत्य संबंध सुदृढ़ होंगे। जीवनसाथी की सलाह उपयोगी साबित होगी।",
                loveReadingEn = "Marital ties strengthen. Advice from spouse proves extremely valuable.",
                financeReadingHi = "आर्थिक स्थिति सामान्य से बेहतर रहेगी। बचत में वृद्धि।",
                financeReadingEn = "Financial condition improves. Good day for systematic savings."
            ),
            RashifalData(
                rashiId = 7, rashiNameEn = "Libra", rashiNameHi = "तुला (Libra)", symbol = "♎",
                elementHi = "वायु (Air)", rulerHi = "शुक्र (Venus)", ratingStars = 5,
                luckyNumber = 6, luckyColorEn = "Blue", luckyColorHi = "आसमानी व नीला", luckyStoneHi = "ओपल (Opal)",
                generalReadingHi = "कला एवं सौंदर्य के प्रति रुझान रहेगा। संतुलन एवं न्यायप्रियता से निर्णय लें।",
                generalReadingEn = "Appreciation for art and aesthetics. Decisions made with balance prove fruitful.",
                careerReadingHi = "फैशन, कला, डिजाइनिंग व व्यापार में नए अवसर। साझेदारी से लाभ।",
                careerReadingEn = "New doors open in design, art, and retail business partnerships.",
                healthReadingHi = "त्वचा एवं सौंदर्य में निखार आएगा। पर्याप्त जलपान करें।",
                healthReadingEn = "Glowing skin and energy. Stay well-hydrated throughout the day.",
                loveReadingHi = "प्रेम संबंध विवाह में बदलने के योग बन रहे हैं। सुखद माहौल।",
                loveReadingEn = "Relationship may head towards marriage. Pleasant romantic vibes.",
                financeReadingHi = "अचानक धन लाभ की संभावना है। व्यापारिक लाभ बढ़ेगा।",
                financeReadingEn = "Unexpected monetary gains and increased commercial turnover."
            ),
            RashifalData(
                rashiId = 8, rashiNameEn = "Scorpio", rashiNameHi = "वृश्चिक (Scorpio)", symbol = "♏",
                elementHi = "जल (Water)", rulerHi = "मंगल (Mars)", ratingStars = 4,
                luckyNumber = 9, luckyColorEn = "Maroon", luckyColorHi = "लाल व मैरून", luckyStoneHi = "मूंगा (Red Coral)",
                generalReadingHi = "गूढ़ विषयों एवं अनुसंधान में रुचि बढ़ेगी। गुप्त शत्रुओं से सावधान रहें।",
                generalReadingEn = "Deep interest in research and mysteries. Stay watchful of hidden competitors.",
                careerReadingHi = "कठिन से कठिन चुनौतियों का सफलतापूर्वक सामना करेंगे।",
                careerReadingEn = "Remarkable capacity to overcome tough professional obstacles.",
                healthReadingHi = "नियमित व्यायाम करें। वाहन सावधानीपूर्वक चलाएं।",
                healthReadingEn = "Maintain routine workouts and drive attentively.",
                loveReadingHi = "साथी के प्रति वफादारी बढ़ेगी। गहन भावनात्मक जुड़ाव।",
                loveReadingEn = "Unwavering loyalty and deep emotional intimacy with partner.",
                financeReadingHi = "पैतृक संपत्ति से लाभ की संभावना। अनावश्यक खर्चों पर रोक लगाएं।",
                financeReadingEn = "Gains from ancestral property. Restrain impulsive expenses."
            ),
            RashifalData(
                rashiId = 9, rashiNameEn = "Sagittarius", rashiNameHi = "धनु (Sagittarius)", symbol = "♐",
                elementHi = "अग्नि (Fire)", rulerHi = "गुरु (Jupiter)", ratingStars = 5,
                luckyNumber = 3, luckyColorEn = "Saffron", luckyColorHi = "पीला व केसरिया", luckyStoneHi = "पुखराज (Yellow Sapphire)",
                generalReadingHi = "धर्म-कर्म एवं धार्मिक यात्रा का योग है। गुरुजनों एवं बड़ों का मार्गदर्शन मिलेगा।",
                generalReadingEn = "Spiritual inclination and travel indicated. Blessings from elders.",
                careerReadingHi = "उच्च शिक्षा, शोध व परामर्श कार्यों में नाम चमकेगा।",
                careerReadingEn = "Excellence in higher academics, research, and advisory services.",
                healthReadingHi = "स्वास्थ्य शानदार रहेगा। मन में प्रसन्नता बनी रहेगी।",
                healthReadingEn = "Splendid health and cheerful mental state.",
                loveReadingHi = "दाम्पत्य जीवन में प्रेम व सामंजस्य बना रहेगा।",
                loveReadingEn = "Abundant love and harmony in married life.",
                financeReadingHi = "भाग्य का पूर्ण सहयोग मिलेगा। नए निवेश लाभदायक रहेंगे।",
                financeReadingEn = "Full luck backing. Long-term investments prove lucrative."
            ),
            RashifalData(
                rashiId = 10, rashiNameEn = "Capricorn", rashiNameHi = "मकर (Capricorn)", symbol = "♑",
                elementHi = "पृथ्वी (Earth)", rulerHi = "शनि (Saturn)", ratingStars = 4,
                luckyNumber = 8, luckyColorEn = "Dark Blue", luckyColorHi = "गहरा नीला व काला", luckyStoneHi = "नीलम (Blue Sapphire)",
                generalReadingHi = "कड़ी मेहनत का फल अवश्य मिलेगा। व्यावहारिक सोच से सफलता प्राप्त होगी।",
                generalReadingEn = "Hard work pays off rewarding dividends. Practical mindset yields results.",
                careerReadingHi = "इंजीनियरिंग, निर्माण व रियल एस्टेट में प्रगति के संकेत।",
                careerReadingEn = "Steady progress in engineering, construction, and real estate.",
                healthReadingHi = "जोड़ों व घुटनों की देखभाल करें। सुबह टहलना लाभदायक।",
                healthReadingEn = "Take care of joints and knees. Morning walks are highly recommended.",
                loveReadingHi = "जीवनसाथी के साथ समय बिताने से दूरियां मिटेंगी।",
                loveReadingEn = "Spending quality time dissolves misunderstandings with partner.",
                financeReadingHi = "स्थायी संपत्ति में वृद्धि होगी। पुराना निवेश फल देगा।",
                financeReadingEn = "Growth in fixed assets. Old investments start giving returns."
            ),
            RashifalData(
                rashiId = 11, rashiNameEn = "Aquarius", rashiNameHi = "कुंभ (Aquarius)", symbol = "♒",
                elementHi = "वायु (Air)", rulerHi = "शनि (Saturn)", ratingStars = 4,
                luckyNumber = 8, luckyColorEn = "Purple", luckyColorHi = "बैंगनी व नीला", luckyStoneHi = "नीलम (Blue Sapphire)",
                generalReadingHi = "नवाचार व सामाजिक कार्यों में मन लगेगा। मित्रों के सहयोग से काम पूरे होंगे।",
                generalReadingEn = "Innovative ideas and social causes inspire you. Friends support whole-heartedly.",
                careerReadingHi = "तकनीकी क्षेत्र व स्टार्ट-अप्स से जुड़े लोगों को बड़ा लाभ।",
                careerReadingEn = "Substantial gains for tech professionals and startup founders.",
                healthReadingHi = "शरीर में जल की मात्रा संतुलित रखें। योगाभ्यास करें।",
                healthReadingEn = "Maintain hydration and engage in light yoga.",
                loveReadingHi = "मित्रता प्रेम संबंध में बदल सकती है। खुशनुमा माहौल।",
                loveReadingEn = "Close friendship may bloom into romance. Joyful times ahead.",
                financeReadingHi = "आर्थिक स्थिति सुदृढ़ होगी। नए व्यापारिक सौदे संभव।",
                financeReadingEn = "Solid financial grounding. High chances of lucrative deal closures."
            ),
            RashifalData(
                rashiId = 12, rashiNameEn = "Pisces", rashiNameHi = "मीन (Pisces)", symbol = "♓",
                elementHi = "जल (Water)", rulerHi = "गुरु (Jupiter)", ratingStars = 5,
                luckyNumber = 3, luckyColorEn = "Gold", luckyColorHi = "सुनहरा व हल्का पीला", luckyStoneHi = "पुखराज (Yellow Sapphire)",
                generalReadingHi = "आध्यात्मिक शांति एवं आत्मिक आनंद की अनुभूति। रचनात्मक कार्यों में मन लगेगा।",
                generalReadingEn = "Spiritual tranquility and inner joy. Creative pursuits flourish.",
                careerReadingHi = "कला, संगीत, योग एवं जनसेवा से जुड़े लोगों को मान-सम्मान।",
                careerReadingEn = "Recognition for professionals in art, music, yoga, and philanthropy.",
                healthReadingHi = "मानसिक शांति बनी रहेगी। ध्यान लगाने से विशेष ऊर्जा।",
                healthReadingEn = "Mental calm and renewed spiritual energy through meditation.",
                loveReadingHi = "जीवनसाथी का स्नेह व केयर दिल को छू लेगी।",
                loveReadingEn = "Affectionate care from spouse fills your heart with warmth.",
                financeReadingHi = "धन का आवक बना रहेगा। दान-पुण्य में खर्च करेंगे।",
                financeReadingEn = "Steady inflow of funds. Charitable donations bring auspicious blessings."
            )
        )
    }
}
